# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                https://Josh-Staske-Booth-App-Development.github.io".
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Josh Staske
  url:               https://twitter.com/
  email:             josh.staske@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
